In [1]:
import pandas as pd
data_bad = pd.read_table('/home/zhongjuliu/database/金融/模型/order_risk_new/ious_order_risk_samples_feature_merge_temp.txt')

In [2]:
data_bad.rename(columns=lambda x: x.split('.')[1], inplace=True)

In [5]:
describe = data_bad.describe([0.05, .25, .5, .75, 0.95])
describe = describe.T

In [6]:
describe

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
      <th>mean</th>
      <th>std</th>
      <th>min</th>
      <th>5%</th>
      <th>25%</th>
      <th>50%</th>
      <th>75%</th>
      <th>95%</th>
      <th>max</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>user_id</th>
      <td>53885.0</td>
      <td>1.728198e+08</td>
      <td>5.373111e+07</td>
      <td>1374.00</td>
      <td>9942160.0</td>
      <td>1.471292e+08</td>
      <td>177499674.0</td>
      <td>210639943.0</td>
      <td>2.403546e+08</td>
      <td>2.593562e+08</td>
    </tr>
    <tr>
      <th>od_days</th>
      <td>53885.0</td>
      <td>7.011246e+01</td>
      <td>7.315163e+01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>90.0</td>
      <td>137.0</td>
      <td>1.850000e+02</td>
      <td>1.990000e+02</td>
    </tr>
    <tr>
      <th>fst_od_days</th>
      <td>53885.0</td>
      <td>7.010019e+01</td>
      <td>7.314354e+01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>90.0</td>
      <td>137.0</td>
      <td>1.850000e+02</td>
      <td>1.990000e+02</td>
    </tr>
    <tr>
      <th>label</th>
      <td>53885.0</td>
      <td>5.038694e-01</td>
      <td>4.999897e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>ious_amount</th>
      <td>53885.0</td>
      <td>4.762562e+02</td>
      <td>6.649443e+02</td>
      <td>0.11</td>
      <td>40.5</td>
      <td>1.175000e+02</td>
      <td>238.0</td>
      <td>600.0</td>
      <td>1.600000e+03</td>
      <td>1.949400e+04</td>
    </tr>
    <tr>
      <th>pay_amount</th>
      <td>53885.0</td>
      <td>4.797416e+02</td>
      <td>6.754665e+02</td>
      <td>1.00</td>
      <td>40.5</td>
      <td>1.188800e+02</td>
      <td>240.0</td>
      <td>605.0</td>
      <td>1.608000e+03</td>
      <td>2.443700e+04</td>
    </tr>
    <tr>
      <th>type_one</th>
      <td>53885.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>type_two</th>
      <td>53885.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>type_three</th>
      <td>53885.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>type_four</th>
      <td>53885.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>type_five</th>
      <td>53885.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>is_app_system</th>
      <td>53885.0</td>
      <td>9.775262e-01</td>
      <td>1.482198e-01</td>
      <td>0.00</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>client_os</th>
      <td>53885.0</td>
      <td>4.210634e-01</td>
      <td>1.340120e+00</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>1.0</td>
      <td>2.0</td>
      <td>2.000000e+00</td>
      <td>2.000000e+00</td>
    </tr>
    <tr>
      <th>is_exist_ip</th>
      <td>53885.0</td>
      <td>9.999443e-01</td>
      <td>7.461371e-03</td>
      <td>0.00</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_exist_device_id</th>
      <td>53885.0</td>
      <td>9.811450e-01</td>
      <td>1.360140e-01</td>
      <td>0.00</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_credible_device</th>
      <td>53885.0</td>
      <td>9.566113e-01</td>
      <td>2.037324e-01</td>
      <td>0.00</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>client_ip_province_risk1</th>
      <td>53885.0</td>
      <td>9.678018e-02</td>
      <td>2.956610e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>client_ip_province_risk2</th>
      <td>53885.0</td>
      <td>2.005753e-01</td>
      <td>4.004345e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>client_ip_province_risk3</th>
      <td>53885.0</td>
      <td>1.684699e-01</td>
      <td>3.742865e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>client_ip_province_risk4</th>
      <td>53885.0</td>
      <td>5.341561e-01</td>
      <td>4.988366e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_client_city_code_lower_risk</th>
      <td>53885.0</td>
      <td>1.152454e-01</td>
      <td>3.193209e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_client_city_code_born</th>
      <td>53885.0</td>
      <td>1.338591e-01</td>
      <td>3.405041e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_client_city_code_live</th>
      <td>53885.0</td>
      <td>2.703350e-01</td>
      <td>4.441370e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_client_city_code_contact</th>
      <td>53885.0</td>
      <td>2.802821e-01</td>
      <td>4.491412e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_client_city_code_dept</th>
      <td>53885.0</td>
      <td>2.899137e-01</td>
      <td>4.537263e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_client_city_code_arrv</th>
      <td>53885.0</td>
      <td>1.797717e-01</td>
      <td>3.840008e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_client_city_code_international</th>
      <td>53885.0</td>
      <td>1.855804e-05</td>
      <td>4.307904e-03</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_client_city_code_his_dept</th>
      <td>53885.0</td>
      <td>6.517027e-01</td>
      <td>4.764352e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_client_city_code_his_arrv</th>
      <td>53885.0</td>
      <td>6.443908e-01</td>
      <td>4.787019e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>is_client_city_code_two_dept</th>
      <td>53885.0</td>
      <td>3.394822e-01</td>
      <td>4.735380e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>holiday_success_amount_avg</th>
      <td>53885.0</td>
      <td>3.531069e+00</td>
      <td>1.686300e+02</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>-1.0</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>1.949400e+04</td>
    </tr>
    <tr>
      <th>holiday_success_amount_max</th>
      <td>53885.0</td>
      <td>3.751322e+00</td>
      <td>1.763181e+02</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>-1.0</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>1.949400e+04</td>
    </tr>
    <tr>
      <th>holiday_refund_amount</th>
      <td>53885.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>holiday_refund_count</th>
      <td>53885.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>holiday_cancel_amount</th>
      <td>53885.0</td>
      <td>1.274412e+01</td>
      <td>5.253997e+02</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>8.584100e+04</td>
    </tr>
    <tr>
      <th>holiday_cancel_count</th>
      <td>53885.0</td>
      <td>9.891435e-03</td>
      <td>2.723809e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>2.700000e+01</td>
    </tr>
    <tr>
      <th>holiday_first_class_count</th>
      <td>53885.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.000000e+00</td>
    </tr>
    <tr>
      <th>holiday_aboard_count</th>
      <td>53885.0</td>
      <td>3.526028e-04</td>
      <td>1.877458e-02</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>1.000000e+00</td>
    </tr>
    <tr>
      <th>holiday_order_before_avg</th>
      <td>53885.0</td>
      <td>-3.923889e+00</td>
      <td>1.969349e+02</td>
      <td>-17288.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>-1.0</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>7.416667e+01</td>
    </tr>
    <tr>
      <th>debit_count</th>
      <td>53885.0</td>
      <td>1.083790e-01</td>
      <td>1.002327e+00</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>3.000000e+00</td>
    </tr>
    <tr>
      <th>debit_self_count</th>
      <td>53885.0</td>
      <td>-1.229470e-01</td>
      <td>8.576216e-01</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>1.000000e+00</td>
      <td>3.000000e+00</td>
    </tr>
    <tr>
      <th>debit_pay_count</th>
      <td>53885.0</td>
      <td>5.873063e-01</td>
      <td>2.834983e+00</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>6.000000e+00</td>
      <td>5.400000e+01</td>
    </tr>
    <tr>
      <th>debit_pay_amount</th>
      <td>53885.0</td>
      <td>5.088864e+02</td>
      <td>1.898667e+03</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>39.0</td>
      <td>2.830294e+03</td>
      <td>9.924250e+04</td>
    </tr>
    <tr>
      <th>debit_pay_amount_max</th>
      <td>53885.0</td>
      <td>2.767527e+02</td>
      <td>9.013351e+02</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>33.6</td>
      <td>1.577930e+03</td>
      <td>2.270100e+04</td>
    </tr>
    <tr>
      <th>credit_count</th>
      <td>53885.0</td>
      <td>-1.760972e-01</td>
      <td>8.627299e-01</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.000000e+00</td>
      <td>1.400000e+01</td>
    </tr>
    <tr>
      <th>credit_self_count</th>
      <td>53885.0</td>
      <td>-2.708917e-01</td>
      <td>7.397983e-01</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.000000e+00</td>
      <td>1.000000e+01</td>
    </tr>
    <tr>
      <th>credit_pay_count</th>
      <td>53885.0</td>
      <td>-1.391853e-03</td>
      <td>2.257991e+00</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>3.000000e+00</td>
      <td>1.970000e+02</td>
    </tr>
    <tr>
      <th>credit_pay_amount</th>
      <td>53885.0</td>
      <td>2.547583e+02</td>
      <td>1.995588e+03</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.055800e+03</td>
      <td>1.423230e+05</td>
    </tr>
    <tr>
      <th>credit_pay_amount_max</th>
      <td>53885.0</td>
      <td>1.363597e+02</td>
      <td>8.083922e+02</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>6.790000e+02</td>
      <td>3.006200e+04</td>
    </tr>
    <tr>
      <th>debit_count_ratio</th>
      <td>53885.0</td>
      <td>4.329305e+01</td>
      <td>4.835108e+01</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>100.0</td>
      <td>1.000000e+02</td>
      <td>1.000000e+02</td>
    </tr>
    <tr>
      <th>credit_count_ratio</th>
      <td>53885.0</td>
      <td>1.510823e+01</td>
      <td>3.413635e+01</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.000000e+02</td>
      <td>1.000000e+02</td>
    </tr>
    <tr>
      <th>credit_count_radio</th>
      <td>53885.0</td>
      <td>2.302320e+01</td>
      <td>4.197996e+01</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>-1.0</td>
      <td>25.0</td>
      <td>1.000000e+02</td>
      <td>1.000000e+02</td>
    </tr>
    <tr>
      <th>credit_pay_count_ratio</th>
      <td>53885.0</td>
      <td>8.077220e+00</td>
      <td>2.706896e+01</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>-1.0</td>
      <td>0.0</td>
      <td>1.000000e+02</td>
      <td>1.000000e+02</td>
    </tr>
    <tr>
      <th>debit_pay_amount_ratio</th>
      <td>53885.0</td>
      <td>2.340468e+01</td>
      <td>4.237893e+01</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>-1.0</td>
      <td>28.0</td>
      <td>1.000000e+02</td>
      <td>1.000000e+02</td>
    </tr>
    <tr>
      <th>credit_pay_amount_ratio</th>
      <td>53885.0</td>
      <td>7.669036e+00</td>
      <td>2.670229e+01</td>
      <td>-1.00</td>
      <td>-1.0</td>
      <td>-1.000000e+00</td>
      <td>-1.0</td>
      <td>0.0</td>
      <td>1.000000e+02</td>
      <td>1.000000e+02</td>
    </tr>
    <tr>
      <th>login_city_count_one</th>
      <td>53885.0</td>
      <td>1.100306e-01</td>
      <td>3.440596e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.000000e+00</td>
      <td>4.000000e+00</td>
    </tr>
    <tr>
      <th>login_city_count_seven</th>
      <td>53885.0</td>
      <td>2.744920e-01</td>
      <td>5.504230e-01</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1.000000e+00</td>
      <td>6.000000e+00</td>
    </tr>
    <tr>
      <th>verify_phone_count</th>
      <td>53885.0</td>
      <td>7.237636e-04</td>
      <td>3.472422e-02</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>3.000000e+00</td>
    </tr>
    <tr>
      <th>verify_discity_phone_count</th>
      <td>53885.0</td>
      <td>1.855804e-04</td>
      <td>1.827612e-02</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>3.000000e+00</td>
    </tr>
    <tr>
      <th>verify_password_count</th>
      <td>53885.0</td>
      <td>1.113482e-03</td>
      <td>3.550676e-02</td>
      <td>0.00</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000e+00</td>
      <td>3.000000e+00</td>
    </tr>
  </tbody>
</table>
<p>295 rows × 10 columns</p>
</div>

In [ ]:
describe = features.describe([0.05, .25, .5, .75, 0.95])
describe = describe.T
describe['std'] = np.round(describe['std'], 2)
describe['mean'] = np.round(describe['mean'], 2)
describe['nuniques'] = features.nunique()
describe['notnull_ratio'] = np.round(describe['count'] * 100. / features.shape[0])
describe['notzero_ratio'] = np.round([features[c].nonzero()[0].size * 100. / features.shape[0] for c in features.columns])

In [4]:
data_bad.describe()

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>user_id</th>
      <th>od_days</th>
      <th>fst_od_days</th>
      <th>label</th>
      <th>ious_amount</th>
      <th>pay_amount</th>
      <th>type_one</th>
      <th>type_two</th>
      <th>type_three</th>
      <th>type_four</th>
      <th>...</th>
      <th>credit_count_ratio</th>
      <th>credit_count_radio</th>
      <th>credit_pay_count_ratio</th>
      <th>debit_pay_amount_ratio</th>
      <th>credit_pay_amount_ratio</th>
      <th>login_city_count_one</th>
      <th>login_city_count_seven</th>
      <th>verify_phone_count</th>
      <th>verify_discity_phone_count</th>
      <th>verify_password_count</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>5.388500e+04</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.0</td>
      <td>53885.0</td>
      <td>53885.0</td>
      <td>53885.0</td>
      <td>...</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
      <td>53885.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>1.728198e+08</td>
      <td>70.112462</td>
      <td>70.100195</td>
      <td>0.503869</td>
      <td>476.256155</td>
      <td>479.741638</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>...</td>
      <td>15.108230</td>
      <td>23.023198</td>
      <td>8.077220</td>
      <td>23.404677</td>
      <td>7.669036</td>
      <td>0.110031</td>
      <td>0.274492</td>
      <td>0.000724</td>
      <td>0.000186</td>
      <td>0.001113</td>
    </tr>
    <tr>
      <th>std</th>
      <td>5.373111e+07</td>
      <td>73.151627</td>
      <td>73.143543</td>
      <td>0.499990</td>
      <td>664.944284</td>
      <td>675.466513</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>...</td>
      <td>34.136347</td>
      <td>41.979958</td>
      <td>27.068963</td>
      <td>42.378932</td>
      <td>26.702288</td>
      <td>0.344060</td>
      <td>0.550423</td>
      <td>0.034724</td>
      <td>0.018276</td>
      <td>0.035507</td>
    </tr>
    <tr>
      <th>min</th>
      <td>1.374000e+03</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.110000</td>
      <td>1.000000</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>...</td>
      <td>-1.000000</td>
      <td>-1.000000</td>
      <td>-1.000000</td>
      <td>-1.000000</td>
      <td>-1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>1.471292e+08</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>117.500000</td>
      <td>118.880000</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>...</td>
      <td>-1.000000</td>
      <td>-1.000000</td>
      <td>-1.000000</td>
      <td>-1.000000</td>
      <td>-1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>1.774997e+08</td>
      <td>90.000000</td>
      <td>90.000000</td>
      <td>1.000000</td>
      <td>238.000000</td>
      <td>240.000000</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>...</td>
      <td>0.000000</td>
      <td>-1.000000</td>
      <td>-1.000000</td>
      <td>-1.000000</td>
      <td>-1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>2.106399e+08</td>
      <td>137.000000</td>
      <td>137.000000</td>
      <td>1.000000</td>
      <td>600.000000</td>
      <td>605.000000</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>...</td>
      <td>0.000000</td>
      <td>25.000000</td>
      <td>0.000000</td>
      <td>28.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>2.593562e+08</td>
      <td>199.000000</td>
      <td>199.000000</td>
      <td>1.000000</td>
      <td>19494.000000</td>
      <td>24437.000000</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>...</td>
      <td>100.000000</td>
      <td>100.000000</td>
      <td>100.000000</td>
      <td>100.000000</td>
      <td>100.000000</td>
      <td>4.000000</td>
      <td>6.000000</td>
      <td>3.000000</td>
      <td>3.000000</td>
      <td>3.000000</td>
    </tr>
  </tbody>
</table>
<p>8 rows × 295 columns</p>
</div>

In [23]:
data_bad_mode = data_bad.mode().T

In [24]:
data_bad_mode.to_csv('data_bad_mode.csv')

In [5]:
feature_des = data_bad.describe().loc[['min', 'mean', 'max', 'std']].T

In [6]:
feature_des.to_csv('feature_des.csv')

In [9]:
type(data_bad)

pandas.core.frame.DataFrame

In [17]:
data_bad_corr = data_bad.corr()['label']

In [18]:
data_bad_corr.to_csv('data_bad_corr.csv')

In [14]:
import scipy.stats as stats
stats.pearsonr(data_bad['od_days'], data_bad['label'])

(0.95107400723056368, 0.0)